apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-web
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/TranChucThien/gitops-demo.git
        revision: main
        directories:
          - path: argocd/applicationset-demo/main/*
          - path: argocd/applicationset-demo/uat/*
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-{{ .path.basenameNormalized }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/TranChucThien/gitops-demo.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 }}-{{ .path.basenameNormalized }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
