apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/TranChucThien/gitops-demo.git
        revision: main
        directories:
          - path: platform/*
  template:
    metadata:
      name: 'platform-{{ .path.basenameNormalized }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if eq .path.basename "cert-manager" }}0{{ else if eq .path.basename "ingress-nginx" }}1{{ else }}2{{ end }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/TranChucThien/gitops-demo.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        name: in-cluster
        namespace: '{{ index .path.segments 1 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/managed-by: argocd
            app.kubernetes.io/part-of: platform
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
          - SkipDryRunOnMissingResource=true
