global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true

server:
  enabled: true
  dev:
    enabled: true
    devRootToken: root

  service:
    enabled: true
    type: ClusterIP
    port: 8200
    targetPort: 8200

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: local-selfsigned
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: vault.vault.ingress.chucthien.com
        paths:
          - /
    tls:
      - secretName: vault-local-tls
        hosts:
          - vault.vault.ingress.chucthien.com

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ui:
  enabled: true
  serviceType: ClusterIP
  externalPort: 8200
